// Generated by tools/generate_mobile_dtos.py from pinned revision 2. Do not hand edit.
package com.example.finance_planning.network.mobile

import org.json.JSONObject

/** Typed boundary; request validation and identity/result ownership are injected. No client construction. */
class MobileBackendDataSource(private val service: MobileBackendService, private val executor: MobileRequestExecutor) {
    suspend fun syncStatus(): OwnedMobileResult<SyncStatusDto> =
        executor.execute("syncStatus", false, JSONObject(),
            JSONObject(), null) { headers, context ->
            service.syncStatus(headers, context)
        }

    suspend fun adminSources(`limit`: Int? = null, `cursor`: String? = null): OwnedMobileResult<AdminSourcePageDto> =
        executor.execute("adminSources", false, JSONObject(),
            JSONObject().apply { `limit`?.let { put("limit", it) } }.apply { `cursor`?.let { put("cursor", it) } }, null) { headers, context ->
            service.adminSources(`limit`, `cursor`, headers, context)
        }

    suspend fun adminRecords(`source`: String, `limit`: Int? = null, `cursor`: String? = null): OwnedMobileResult<AdminRecordPageDto> =
        executor.execute("adminRecords", false, JSONObject().put("source", `source`),
            JSONObject().apply { `limit`?.let { put("limit", it) } }.apply { `cursor`?.let { put("cursor", it) } }, null) { headers, context ->
            service.adminRecords(`source`, `limit`, `cursor`, headers, context)
        }

    suspend fun allPlanning(`view`: String? = null, `limit`: Int? = null, `cursor`: String? = null): OwnedMobileResult<PlanningPageDto> =
        executor.execute("allPlanning", false, JSONObject(),
            JSONObject().apply { `view`?.let { put("view", it) } }.apply { `limit`?.let { put("limit", it) } }.apply { `cursor`?.let { put("cursor", it) } }, null) { headers, context ->
            service.allPlanning(`view`, `limit`, `cursor`, headers, context)
        }

    suspend fun planningIntent(`intent_id`: String): OwnedMobileResult<PlanningIntentDto> =
        executor.execute("planningIntent", false, JSONObject().put("intent_id", `intent_id`),
            JSONObject(), null) { headers, context ->
            service.planningIntent(`intent_id`, headers, context)
        }

    suspend fun planningSource(): OwnedMobileResult<PlanningSourceDto> =
        executor.execute("planningSource", false, JSONObject(),
            JSONObject(), null) { headers, context ->
            service.planningSource(headers, context)
        }

    suspend fun planningPreflight(`intent_id`: String, body: PreflightRequest): OwnedMobileResult<PreflightResultDto> =
        executor.execute("planningPreflight", true, JSONObject().put("intent_id", `intent_id`),
            JSONObject(), body) { headers, context ->
            service.planningPreflight(`intent_id`, body, headers, context)
        }

    suspend fun importPlanning(): OwnedMobileResult<LegacyImportResultDto> =
        executor.execute("importPlanning", true, JSONObject(),
            JSONObject(), null) { headers, context ->
            service.importPlanning(headers, context)
        }

    suspend fun retryProjection(): OwnedMobileResult<ProjectionResultDto> =
        executor.execute("retryProjection", true, JSONObject(),
            JSONObject(), null) { headers, context ->
            service.retryProjection(headers, context)
        }

    suspend fun reconcile(): OwnedMobileResult<ProjectionResultDto> =
        executor.execute("reconcile", true, JSONObject(),
            JSONObject(), null) { headers, context ->
            service.reconcile(headers, context)
        }

    suspend fun upload(body: SyncBatch): OwnedMobileResult<UploadResultDto> =
        executor.execute("upload", true, JSONObject(),
            JSONObject(), body) { headers, context ->
            service.upload(body, headers, context)
        }

    suspend fun placedOrder(body: PlacedOrderUpdate): OwnedMobileResult<LegacyPlacedResultDto> =
        executor.execute("placedOrder", true, JSONObject(),
            JSONObject(), body) { headers, context ->
            service.placedOrder(body, headers, context)
        }

    suspend fun placedOrderV2(body: PlacedOrderUpdateV2): OwnedMobileResult<PlacedIntentResultDto> =
        executor.execute("placedOrderV2", true, JSONObject(),
            JSONObject(), body) { headers, context ->
            service.placedOrderV2(body, headers, context)
        }

    suspend fun batches(`limit`: Int? = null, `cursor`: String? = null, `source`: String? = null): OwnedMobileResult<BatchPageDto> =
        executor.execute("batches", false, JSONObject(),
            JSONObject().apply { `limit`?.let { put("limit", it) } }.apply { `cursor`?.let { put("cursor", it) } }.apply { `source`?.let { put("source", it) } }, null) { headers, context ->
            service.batches(`limit`, `cursor`, `source`, headers, context)
        }

    suspend fun batch(`batch_id`: String, `source`: String? = null): OwnedMobileResult<BatchDetailDto> =
        executor.execute("batch", false, JSONObject().put("batch_id", `batch_id`),
            JSONObject().apply { `source`?.let { put("source", it) } }, null) { headers, context ->
            service.batch(`batch_id`, `source`, headers, context)
        }

    suspend fun orders(`limit`: Int? = null, `cursor`: String? = null, `source`: String? = null): OwnedMobileResult<OrderPageDto> =
        executor.execute("orders", false, JSONObject(),
            JSONObject().apply { `limit`?.let { put("limit", it) } }.apply { `cursor`?.let { put("cursor", it) } }.apply { `source`?.let { put("source", it) } }, null) { headers, context ->
            service.orders(`limit`, `cursor`, `source`, headers, context)
        }

    suspend fun order(`account`: String, `order_id`: String, `source`: String? = null, `environment`: String? = null): OwnedMobileResult<BrokerOrderDto> =
        executor.execute("order", false, JSONObject().put("account", `account`).put("order_id", `order_id`),
            JSONObject().apply { `source`?.let { put("source", it) } }.apply { `environment`?.let { put("environment", it) } }, null) { headers, context ->
            service.order(`account`, `order_id`, `source`, `environment`, headers, context)
        }

    suspend fun notifications(`limit`: Int? = null, `cursor`: String? = null): OwnedMobileResult<NotificationPageDto> =
        executor.execute("notifications", false, JSONObject(),
            JSONObject().apply { `limit`?.let { put("limit", it) } }.apply { `cursor`?.let { put("cursor", it) } }, null) { headers, context ->
            service.notifications(`limit`, `cursor`, headers, context)
        }

    suspend fun notification(`event_id`: String): OwnedMobileResult<NotificationDto> =
        executor.execute("notification", false, JSONObject().put("event_id", `event_id`),
            JSONObject(), null) { headers, context ->
            service.notification(`event_id`, headers, context)
        }

    suspend fun notificationPlan(`plan_id`: String): OwnedMobileResult<NotificationPlanDto> =
        executor.execute("notificationPlan", false, JSONObject().put("plan_id", `plan_id`),
            JSONObject(), null) { headers, context ->
            service.notificationPlan(`plan_id`, headers, context)
        }

    suspend fun registerDevice(`device_id`: String, body: DeviceRegistration): OwnedMobileResult<DeviceRegistrationResultDto> =
        executor.execute("registerDevice", true, JSONObject().put("device_id", `device_id`),
            JSONObject(), body) { headers, context ->
            service.registerDevice(`device_id`, body, headers, context)
        }

    suspend fun removeDevice(`device_id`: String): OwnedMobileResult<DeviceRegistrationResultDto> =
        executor.execute("removeDevice", true, JSONObject().put("device_id", `device_id`),
            JSONObject(), null) { headers, context ->
            service.removeDevice(`device_id`, headers, context)
        }

    suspend fun receipt(`event_id`: String, body: NotificationReceipt): OwnedMobileResult<ReceiptResultDto> =
        executor.execute("receipt", true, JSONObject().put("event_id", `event_id`),
            JSONObject(), body) { headers, context ->
            service.receipt(`event_id`, body, headers, context)
        }

    suspend fun publishInstruction(body: NotificationCommand): OwnedMobileResult<NotificationPublishResultDto> =
        executor.execute("publishInstruction", true, JSONObject(),
            JSONObject(), body) { headers, context ->
            service.publishInstruction(body, headers, context)
        }

    suspend fun previewNotification(body: PreviewRequest): OwnedMobileResult<PreviewResultDto> =
        executor.execute("previewNotification", true, JSONObject(),
            JSONObject(), body) { headers, context ->
            service.previewNotification(body, headers, context)
        }

    suspend fun health(): MobileHealthResult = executor.health { context -> service.health(context) }

}
