// Generated by tools/generate_mobile_dtos.py from pinned revision 2. Do not hand edit.
package com.example.finance_planning.network.mobile

import org.json.JSONObject

import retrofit2.Response
import retrofit2.http.*

/** Inactive until an explicitly configured, approved client is injected. No dynamic URLs. */
interface MobileBackendService {
    @MobileOperation("syncStatus") @GET("mobile/v1/sync/status")
    suspend fun syncStatus(@HeaderMap headers: Map<String, String>): Response<MobileSuccess<SyncStatusDto>>

    @MobileOperation("adminSources") @GET("mobile/v1/admin/sources")
    suspend fun adminSources(@Query("limit") `limit`: Int? = null, @Query("cursor") `cursor`: String? = null, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<AdminSourcePageDto>>

    @MobileOperation("adminRecords") @GET("mobile/v1/admin/sources/{source}/records")
    suspend fun adminRecords(@Path("source") `source`: String, @Query("limit") `limit`: Int? = null, @Query("cursor") `cursor`: String? = null, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<AdminRecordPageDto>>

    @MobileOperation("allPlanning") @GET("mobile/v1/planning/intents")
    suspend fun allPlanning(@Query("view") `view`: String? = null, @Query("limit") `limit`: Int? = null, @Query("cursor") `cursor`: String? = null, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<PlanningPageDto>>

    @MobileOperation("planningIntent") @GET("mobile/v1/planning/intents/{intent_id}")
    suspend fun planningIntent(@Path("intent_id") `intent_id`: String, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<PlanningIntentDto>>

    @MobileOperation("planningSource") @GET("mobile/v1/planning/source")
    suspend fun planningSource(@HeaderMap headers: Map<String, String>): Response<MobileSuccess<PlanningSourceDto>>

    @MobileOperation("planningPreflight") @POST("mobile/v1/planning/intents/{intent_id}/preflight")
    suspend fun planningPreflight(@Path("intent_id") `intent_id`: String, @Body body: PreflightRequest, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<PreflightResultDto>>

    @MobileOperation("importPlanning") @POST("mobile/v1/legacy/planning/import")
    suspend fun importPlanning(@HeaderMap headers: Map<String, String>): Response<MobileSuccess<LegacyImportResultDto>>

    @MobileOperation("retryProjection") @POST("mobile/v1/sync/retry")
    suspend fun retryProjection(@HeaderMap headers: Map<String, String>): Response<MobileSuccess<ProjectionResultDto>>

    @MobileOperation("reconcile") @POST("mobile/v1/sheets/reconcile")
    suspend fun reconcile(@HeaderMap headers: Map<String, String>): Response<MobileSuccess<ProjectionResultDto>>

    @MobileOperation("upload") @POST("mobile/v1/sync/batches")
    suspend fun upload(@Body body: SyncBatch, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<UploadResultDto>>

    @MobileOperation("placedOrder") @POST("mobile/v1/legacy/orders/placed")
    suspend fun placedOrder(@Body body: PlacedOrderUpdate, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<LegacyPlacedResultDto>>

    @MobileOperation("placedOrderV2") @POST("mobile/v1/orders/placed")
    suspend fun placedOrderV2(@Body body: PlacedOrderUpdateV2, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<PlacedIntentResultDto>>

    @MobileOperation("batches") @GET("mobile/v1/sync/batches")
    suspend fun batches(@Query("limit") `limit`: Int? = null, @Query("cursor") `cursor`: String? = null, @Query("source") `source`: String? = null, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<BatchPageDto>>

    @MobileOperation("batch") @GET("mobile/v1/sync/batches/{batch_id}")
    suspend fun batch(@Path("batch_id") `batch_id`: String, @Query("source") `source`: String? = null, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<BatchDetailDto>>

    @MobileOperation("orders") @GET("mobile/v1/orders")
    suspend fun orders(@Query("limit") `limit`: Int? = null, @Query("cursor") `cursor`: String? = null, @Query("source") `source`: String? = null, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<OrderPageDto>>

    @MobileOperation("order") @GET("mobile/v1/orders/{account}/{order_id}")
    suspend fun order(@Path("account") `account`: String, @Path("order_id") `order_id`: String, @Query("source") `source`: String? = null, @Query("environment") `environment`: String? = null, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<BrokerOrderDto>>

    @MobileOperation("notifications") @GET("mobile/v1/notifications")
    suspend fun notifications(@Query("limit") `limit`: Int? = null, @Query("cursor") `cursor`: String? = null, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<NotificationPageDto>>

    @MobileOperation("notification") @GET("mobile/v1/notifications/{event_id}")
    suspend fun notification(@Path("event_id") `event_id`: String, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<NotificationDto>>

    @MobileOperation("notificationPlan") @GET("mobile/v1/notification-plans/{plan_id}")
    suspend fun notificationPlan(@Path("plan_id") `plan_id`: String, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<NotificationPlanDto>>

    @MobileOperation("registerDevice") @PUT("mobile/v1/devices/{device_id}")
    suspend fun registerDevice(@Path("device_id") `device_id`: String, @Body body: DeviceRegistration, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<DeviceRegistrationResultDto>>

    @MobileOperation("removeDevice") @DELETE("mobile/v1/devices/{device_id}")
    suspend fun removeDevice(@Path("device_id") `device_id`: String, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<DeviceRegistrationResultDto>>

    @MobileOperation("receipt") @POST("mobile/v1/notifications/{event_id}/receipts")
    suspend fun receipt(@Path("event_id") `event_id`: String, @Body body: NotificationReceipt, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<ReceiptResultDto>>

    @MobileOperation("publishInstruction") @POST("mobile/v1/notifications")
    suspend fun publishInstruction(@Body body: NotificationCommand, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<NotificationPublishResultDto>>

    @MobileOperation("previewNotification") @POST("mobile/v1/notification-preview")
    suspend fun previewNotification(@Body body: PreviewRequest, @HeaderMap headers: Map<String, String>): Response<MobileSuccess<PreviewResultDto>>

    @MobileOperation("health") @GET("health")
    suspend fun health(): Response<HealthDto>

}
